export default function Button({children, onClick, className}) {
    return(
        <button
         className={`
            bg-blue-600
            text-white 
            px-2 
            py-1 
            rounded
            hover:bg-blue-700
            transition
            ${className}
        `}
            onClick={onClick}
        >
            {children}
        </button>
    );
}